# Generated by Django 3.1.7 on 2021-04-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='albumn',
            new_name='album',
        ),
    ]
